# docker compose down; docker compose up --build --remove-orphans;

version: "3.7"

services:
  redis:
    container_name: redis
    image: 'redis:alpine'

  event-saver:
    container_name: event-saver
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - 9100:9000
    depends_on:
      - redis
    environment:
      - PORT=9000
      - CLICKHOUSE_HOST=http://host.docker.internal:8123
      - CLICKHOUSE_DATABASE=WOT
      - CLICKHOUSE_USER
      - CLICKHOUSE_PASSWORD
      - JWT_SECRET
      - REDIS_HOST=redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
