# docker compose down; docker compose up --build --remove-orphans;

version: "3.7"

services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:23.12.2.59-alpine
    volumes:
      - ./clickhouse-dev/data:/var/lib/clickhouse
      - ./clickhouse-dev/log:/var/log/clickhouse-server
      - ./clickhouse-dev/config/config.d:/etc/clickhouse-server/config.d
      - ./clickhouse-dev/config/users.d:/etc/clickhouse-server/users.d
      - ./clickhouse-dev/init:/docker-entrypoint-initdb.d
    ports:
      - '8123:8123'

  redis:
    container_name: redis
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  app:
    container_name: app
    restart: always
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - 9000:9000
    depends_on:
      - clickhouse
      - redis
    environment:
      - PORT=9000
      - CLICKHOUSE_HOST=http://clickhouse:8123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DATABASE=WOT
      - JWT_SECRET=JWT_SECRET
      - REDIS_HOST=redis
      - DEBUG=1
