# docker compose down; docker compose up --build --remove-orphans;

services:
  redis:
    container_name: redis
    image: 'redis:alpine'
    networks:
      - bridge

  event-saver:
    container_name: event-saver
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - 9100:9000
    depends_on:
      - redis
    environment:
      - PORT=9000
      - CLICKHOUSE_HOST=http://172.17.0.1:8123
      - CLICKHOUSE_DATABASE=WOT
      - CLICKHOUSE_USER
      - CLICKHOUSE_PASSWORD
      - JWT_SECRET
      - REDIS_HOST=redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      bridge:
        ipv4_address: 172.25.0.10

networks:
  bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
