# docker compose down; docker compose up --build --remove-orphans;
services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:24.2.2-alpine
    volumes:
      - ./docker-volumes/clickhouse-local/data:/var/lib/clickhouse
      - ./docker-volumes/clickhouse-local/log:/var/log/clickhouse-server
      - ./clickhouse-local/config/config.d:/etc/clickhouse-server/config.d
      - ./clickhouse-local/config/users.d:/etc/clickhouse-server/users.d
      - ./clickhouse-local/init:/docker-entrypoint-initdb.d
    ports:
      - '8123:8123'

  clickhouse-backup:
    image: altinity/clickhouse-backup:2.4.29
    restart: always
    volumes_from:
      - clickhouse
    depends_on:
      - clickhouse
    environment:
      - REMOTE_STORAGE=s3
      - API_LISTEN=0.0.0.0:7171
      - CLICKHOUSE_HOST=clickhouse
      - S3_BUCKET=wotstat-backup
      - S3_ENDPOINT=https://storage.yandexcloud.net
      - S3_REGION=ru-central1
      - CLICKHOUSE_USERNAME=default
      - CLICKHOUSE_PASSWORD=
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
    command: [ "sleep", "infinity" ]

  redis:
    container_name: redis
    image: 'redis:alpine'

  app:
    container_name: event-saver
    restart: always
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - 9100:9000
    depends_on:
      - clickhouse
      - redis
    environment:
      - PORT=9000
      - CLICKHOUSE_HOST=http://clickhouse:8123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DATABASE=WOT
      - JWT_SECRET=JWT_SECRET
      - REDIS_HOST=redis
      - DEBUG=1
