# docker compose down; docker compose up --remove-orphans;

version: "3.7"

services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:23.1.3.5-alpine
    volumes:
      - ./clickhouse/data:/var/lib/clickhouse
      - ./clickhouse/log:/var/log/clickhouse-server
      - ./clickhouse/config/config.d:/etc/clickhouse-server/config.d
      # - ./clickhouse/users.d:/etc/clickhouse-server/users.d
      - ./clickhouse/init:/docker-entrypoint-initdb.d
    ports:
      - '8123:8123'

  redis:
    container_name: redis
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  app:
    container_name: app
    restart: always
    build:
      context: ../
      dockerfile: dev/Dockerfile
    volumes:
      - ../src:/app/src
    ports:
      - 9000:9000
    depends_on:
      - clickhouse
      - redis
    environment:
      - PORT=9000
      - CLICKHOUSE_HOST=http://clickhouse:8123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DATABASE=WOT
      - JWT_SECRET=JWT_SECRET
      - REDIS_HOST=redis
      - DEBUG=1
